### ISSUE TITLE
Probably nothing

### ISSUE THREAD

**Issue by DBtheGreat870** [thisisevanfox/nba-my-team-ios-widget#12]
2024-09-12 02:53:23: Error on line 770:36: TypeError: null is not an object (evaluating 'oResponse.payload.team.standings')

Will most likely fix itself after season starts but maybe an if statement to account for the return of null would work. Not sure

**Comment by thisisevanfox** [comment]
Hi @DBtheGreat870,

does the error still occur? I will add an if clause with the next release.

Kind regards
Evan

**Comment by NixPhan** [comment]
Got this error when I first installed. Couldn't fix it so I waited, and by preseason the widget was working properly. Now the same error is back.

2024-10-21 22:48:51: Error on line 793:36: TypeError: null is not an object (evaluating 'oResponse.payload.team.standings')

**Comment by DBtheGreat870** [comment]
It was fixed once preseason started but it’s back now that the stats and
standings have been reset. I guess it doesn’t know how to handle the zeros
so it’s giving an error message.

**Comment by thisisevanfox** [comment]
Which team do you guys use, @NixPhan @DBtheGreat870? Could it be that the error only occurs when live mode is active and a game is in progress?

**Comment by DBtheGreat870** [comment]
Dallas Mavericks is the team I use and I’ve also noticed my live mode is
active yet the games don’t update until final

**Comment by DBtheGreat870** [comment]
Changing the team doesn’t fix the issue also

**Comment by thisisevanfox** [comment]
Thank you, I found the bug. I will publish a fix later.

**Comment by thisisevanfox** [comment]
Resolved with #13.

**Comment by thisisevanfox** [comment]
Hi,

I fixed the bug with release v1.8.1. For updating please refer to the [Installation Guide](https://github.com/thisisevanfox/nba-my-team-ios-widget/blob/main/Installation%20guide.md).

Thank you for your patience! :)

Kind regards
Evan

CC: @DBtheGreat870 @NixPhan
