### ISSUE TITLE
Not showing game on current day?

### ISSUE THREAD

**Issue by boostedgti916** [thisisevanfox/nba-my-team-ios-widget#2]
The widget is great! But its showing the next game and not the game that is coming on today?

**Comment by thisisevanfox** [comment]
Hi,

Thank you for reporting.

Which team did you choose?
Which opponent is shown?
Which opponent should be shown?
Can you provided a screenshot please?

**Comment by boostedgti916** [comment]
![image](https://user-images.githubusercontent.com/42480632/106800369-384f4e80-6615-11eb-8880-85578b5ecca4.jpeg)

I picked the Sacramento kings. They are playing the Celtics tonight. The date says 02/06/20 supposed to be 02/03

**Comment by thisisevanfox** [comment]
In which timezone are you?

For me it's: 
![image](https://user-images.githubusercontent.com/43059689/106805103-89d3f980-6666-11eb-9250-ab3278b19702.jpeg)

**Comment by boostedgti916** [comment]
> In which timezone are you? I think it has something to do with this...
> 
> For me it's: 
> ![image](https://user-images.githubusercontent.com/43059689/106805103-89d3f980-6666-11eb-9250-ab3278b19702.jpeg)
> 

PST

**Comment by thisisevanfox** [comment]
Okay, I'll take a look and keep you updated :)

**Comment by thisisevanfox** [comment]
As a workaround until the next version you can set the following line like this:
![image](https://user-images.githubusercontent.com/43059689/106812823-7af24480-6670-11eb-80e6-68da0cb16803.jpeg)

**Comment by boostedgti916** [comment]
> As a workaround until the next version you can set the following line like this:
> ![image](https://user-images.githubusercontent.com/43059689/106812823-7af24480-6670-11eb-80e6-68da0cb16803.jpeg)

Awesome that worked!! Thank you!

**Comment by many7695** [comment]
I’m having this same issue with Brooklyn  nets  instead of showing the game from today is showing the next game

**Comment by many7695** [comment]
> Hi @many7695, have you tried the workaround mentioned above?

Thanks that worked

**Comment by thisisevanfox** [comment]
Hi, i just published a new release to make the widget work again in the new season. As I'am in another timezone the specified has changed within the new release back to the default value. So when you run in the same issue again you have to change the line like described above. I'll try to fix this problem in future releases.

Will close this issue now. Thanks for reporting!
