### ISSUE TITLE
On day of game, shows upcoming game

### ISSUE THREAD

**Issue by mikemikey96** [thisisevanfox/nba-my-team-ios-widget#6]
On the day of a game, the widget shows the upcoming game instead of today's game.

**Comment by thisisevanfox** [comment]
Hi @mikemikey96,

What timezone are you in? Can you please try the workaround mentioned [here](https://github.com/thisisevanfox/nba-my-team-ios-widget/issues/2#issuecomment-772841607)?

Regards
Evan

**Comment by mikemikey96** [comment]
PST. It is currently 23:14 on 11/23. Changed the value to 24 and it showed me today’s game. Thanks!
