### ISSUE TITLE
Wrong game 

### ISSUE THREAD

**Issue by many7695** [thisisevanfox/nba-my-team-ios-widget#7]
Today the Raptors are playing against Philadelphia but is showing the game against Portland who they play next

**Comment by thisisevanfox** [comment]
Hi @many7695,

What timezone are you in? Can you please try the workaround mentioned [here](https://github.com/thisisevanfox/nba-my-team-ios-widget/issues/2#issuecomment-772841607). Maybe you have to change the value to 24.

Regards
Evan

**Comment by thisisevanfox** [comment]
Hi @many7695,

Were you able to solve the problem? If so, can you please close the issue? Thank you.

Kind Regards,
Evan

**Comment by thisisevanfox** [comment]
Closed due to inactivity
